GeoLocation/Pages/Downloads.cshtml.cs
using GeoLocation.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OfficeOpenXml;

namespace GeoLocation.Pages
{
    public class DownloadsModel : PageModel
    {
        private IWebHostEnvironment Environment;
        public string Message { get; set; }

        public IList<FileModel> ListOfFiles { get; set; }

        public DownloadsModel(IWebHostEnvironment _enviroment)
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            Environment = _enviroment;
            OnGet();
        }
       
        public IActionResult OnPostDeleteFile([System.Web.Http.FromUri] string request)
        {
            try
            {
                string Name = request;//.FileName;

                string path = Path.Combine(this.Environment.WebRootPath, "Upload");
                System.IO.File.Delete(path + "\\" + request);

                OnGet();
                return RedirectToPage();

            }
            catch (Exception ex)
            {
                return RedirectToPage("./Error", "ShowError", new { message = ex.Message });

            }
        }

        public IActionResult OnPostUpload(IList<IFormFile> postedFiles)
        {
            try
            {
                string wwwpath = this.Environment.WebRootPath;
                string contentPath = this.Environment.ContentRootPath;
                string path = Path.Combine(this.Environment.WebRootPath, "Upload");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                List<string> uploadFiles = new List<string>();
                foreach (IFormFile postedFile in postedFiles)
                {
                    string filename = Path.GetFileName(postedFile.FileName);
                    using (FileStream stream = new FileStream(Path.Combine(path, filename), FileMode.Create))
                    {
                        postedFile.CopyTo(stream);
                        uploadFiles.Add(filename);
                        this.Message += string.Format("<b>{0}</b> uploaded. </br>", filename);
                    }

                }
                OnGet();
                return RedirectToPage();


            }
            catch (Exception ex)
            {
                return RedirectToPage("./Error", "ShowError", new { message = ex.Message });

            }
        }

        public void OnGet()
        {
            try
            {
                string path = Path.Combine(this.Environment.WebRootPath, "Upload");
                IList<FileModel> LsfileModel = new List<FileModel>();
                var source = Directory.GetFiles(path);
                int count = 1;
                if (source == null || source.Count() > 0)
                {
                    foreach (var item in source)
                    {
                        FileInfo fileInfo = new FileInfo(item);

                        LsfileModel.Add(new()
                        {
                            Id = count++,
                            Name = fileInfo.Name
                            ,
                            Extension = fileInfo.Extension
                            ,
                            Url = fileInfo.FullName
                            ,
                            Size = (fileInfo.Length > 0 ? (

                            (fileInfo.Length / 1024 > 1024 ?
                                    (fileInfo.Length / (1024 * 1024)).ToString() + " Mb"
                                                : (fileInfo.Length / 1024).ToString() + " Kb")) : "0")
                            ,
                            Description = fileInfo.CreationTime.ToString()
                        });
                    }
                }
                ListOfFiles = LsfileModel;
            }
            catch (Exception ex)
            {
                RedirectToPage("./Error", "ShowError", new { message = ex.Message });

            }
        }


        public IActionResult OnPostDownloadFile([System.Web.Http.FromUri] string request)
        {

            string wwwpath = this.Environment.WebRootPath;
            string contentPath = this.Environment.ContentRootPath;
            string path = Path.Combine(this.Environment.WebRootPath, "Upload");
            string Filepath = Path.Combine(path, request);

            return File(
                Environment
                    .WebRootFileProvider
                    .GetFileInfo(@"\Upload\" + request)
                    .CreateReadStream(),
                GetContentType(Filepath));
        }

        private string GetContentType(string path)
        {
            var types = GetMimeTypes();
            var ext = Path.GetExtension(path).ToLowerInvariant();
            if (types.ContainsKey(ext))
            {
                return types[ext];

            }
            else
                // RedirectToPage("./Error", "ShowError", new { message = "" });
                return "*/*";
        }

        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
            {
                {".txt", "text/txt"},
                {".pdf", "application/pdf"},
                {".doc", "application/vnd.ms-word"},
                {".docx", "application/vnd.ms-word"},
                {".xls", "application/vnd.ms-excel"},
                {".xlsx", "application/vnd.openxmlformatsofficedocument.spreadsheetml.sheet"},
                {".png", "image/png"},
                {".jpg", "image/jpeg"},
                {".jpeg", "image/jpeg"},
                {".gif", "image/gif"},
                {".csv", "text/csv"}
            };
        }
    }
}

GeoLocation/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace GeoLocation.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public string ErrorMessage { get; set; }

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }

        public void OnGetShowError(string message)
        {
            ErrorMessage = message;

            RedirectToPage();

        }
    }
}

GeoLocation/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GeoLocation.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

GeoLocation/Pages/ShowExcel.cshtml.cs
using GeoLocation.Models;
using GeoLocation.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OfficeOpenXml;
using System.IO;
using System.Net.Http;

namespace GeoLocation.Pages
{
    public class ShowExcelModel : PageModel
    {
        private IWebHostEnvironment Environment;
        public CancellationToken cancellationToken { get; set; }
        public static CancellationTokenSource cancellationTokenSource { get; set; }
        public static IList<ExcelData> LsExcelData { get; set; }
        public IList<ExcelData> GridData { get; set; }

        public static string FileNameToProcess { get; set; }

        public int _current = 0;
        public int Current { get { return _current; } set { _current = value; } }
        public ShowExcelModel(IWebHostEnvironment _enviroment)
        {
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            Environment = _enviroment;

            if(cancellationTokenSource==null)
            {
                cancellationTokenSource = new CancellationTokenSource();
            }

        }

       
        public void OnGet()
        {
        }

        public void OnPostNextData(string current)
        {
            ViewData["Sended_File"] = FileNameToProcess;
            int localcurrent = int.Parse(current);
            if (localcurrent < LsExcelData.Count)
            {
                Current = localcurrent + 20;
                GridData = LsExcelData.Skip(Current).Take(20).ToList();

            }
            RedirectToPage();
        }
        public void OnPostEndData(string current)
        {
            ViewData["Sended_File"] = FileNameToProcess;

            Current = 20;
            if (LsExcelData.Count > 20)
            {
                Current = LsExcelData.Count - 20;
                GridData = LsExcelData.Skip(LsExcelData.Count - 20).Take(20).ToList();
            }
            else
                GridData = LsExcelData;
            RedirectToPage();

        }
        public void OnGetFirstData(string filename)
        {
            FileNameToProcess = filename;
            ViewData["Sended_File"] = FileNameToProcess;
            Current = 20;
            GridData = LsExcelData.Take(20).ToList();
            RedirectToPage();

        }

        public void OnPostPreviousData(string current)
        {
            ViewData["Sended_File"] = FileNameToProcess;
            int localcurrent = int.Parse(current);
            if (localcurrent > 20)
            {
                Current = localcurrent - 20;
                GridData = LsExcelData.Skip(localcurrent - 20).Take(20).ToList();
            }
            RedirectToPage();
        }

        public void OnPostSortData(string sort, string data)
        {
            try
            {
            ViewData["Sended_File"] = FileNameToProcess;
                int localcurrent = int.Parse(data);

                GridData = LsExcelData.Skip((localcurrent - 20 > 20 ? localcurrent - 20 : 0)).Take(20).ToList();

                Current = localcurrent;
                if (sort == "asc")
                    GridData = GridData.ToList().OrderBy(c => c.Postalcode).ToList();
                else
                    GridData = GridData.ToList().OrderByDescending(c => c.Postalcode).ToList();
            }
            catch (Exception ex)
            {
                RedirectToPage("./Error", "ShowError", new { message = ex.Message });
            }
        }

        private IList<ExcelData> GetExcelContent(string FileFullpath)
        {
            using (var package = new ExcelPackage(new FileInfo(Path.Combine(FileFullpath))))
            {
                ExcelWorksheet sheet = package.Workbook.Worksheets[0];
                return sheet.ConvertSheetToObjects<ExcelData>().ToList();
            }

        }

        public IActionResult OnGetProcessExcel([System.Web.Http.FromUri] string request)
        {
            try
            {
                ViewData["Sended_File"] = request;
                string path = Path.Combine(this.Environment.WebRootPath, "Upload");

                if (new string[] { ".xlsx", ".csv" }.Any(new FileInfo(Path.Combine(path, request)).Extension.Equals))
                {

                    LsExcelData = GetExcelContent(Path.Combine(path, request));
                    Current = 20;
                    GridData = LsExcelData.Take(20).ToList();
                    return RedirectToPage("./ShowExcel", "FirstData", new { filename = request });// RedirectToPage("./ShowExcel");
                }
                else
                {
                    return RedirectToPage("./Error", "ShowError", new { message = "File Format is not Excel." });
                }
            }
            catch (Exception ex)
            {
                return RedirectToPage("./Error", "ShowError", new { message = ex.Message });
            }
        }

        private string GetUniqueFileNameInPath(string path,string filename,string extensions )
        {
            if (new FileInfo(Path.Combine(path, filename) + ".log").Exists)
            {
                IList<FileInfo> lsFile = new DirectoryInfo(Path.Combine(path)).GetFiles("*"+ extensions + "*.*.csv").OrderBy(c => c.Name).ToList();

                if (lsFile.Count > 0)
                {
                    filename = lsFile[lsFile.Count - 1].Name.Substring(0, lsFile[lsFile.Count - 1].Name.LastIndexOf(".csv"));

                    return filename.Split(extensions).First() + extensions + (int.Parse(filename.Split('.').First().Split(extensions).Last()) + 1) + "." + filename.Split('.').Last();
                }
                else
                    return filename.Split('.').First() + extensions+"1." + filename.Split('.').Last();

            }
            return filename;

        }

        public void OnPostCancelExcelFileProcessed()
        {
            cancellationTokenSource.Cancel();
        }

        public async Task<IActionResult> OnPostGetLocations(string filename)
        {
            try
            {
            ViewData["Sended_File"] = FileNameToProcess;
                string path = Path.Combine(this.Environment.WebRootPath, "Upload");

                LsExcelData = GetExcelContent(Path.Combine(path, filename));
                HttpClient client = new HttpClient();
                client.Timeout = new TimeSpan(0, 5, 0);
                var code = "";
                var responseBody = "";

                filename=GetUniqueFileNameInPath(path, filename, "_Geo");
                int count = 0;

                foreach (var item in LsExcelData)
                {
                    code = item.Postalcode;

                    try
                    {
                        using HttpResponseMessage response = await client.GetAsync("*****" + code);//, cancellationTokenSource.Token);
                        response.EnsureSuccessStatusCode();
                        responseBody = response.Content.ReadAsStringAsync().Result;
                    }
                    catch
                    {
                        responseBody = "";
                    }
                    if(cancellationTokenSource.Token.IsCancellationRequested)
                    {
                        break;
                    }
                    using (System.IO.StreamWriter sw = new StreamWriter(Path.Combine(path, filename) + ".csv", true))
                    {
                        if(count==0)
                            sw.WriteLine($"PostalCode,latitude,longitude");

                        count++;
                        LatLongModel latLongModel =  Newtonsoft.Json.JsonConvert.DeserializeObject<LatLongModel>(responseBody);
                        if(latLongModel!=null)
                            sw.WriteLine($"{code},{latLongModel.latitude},{latLongModel.longitude}");
                        else
                        sw.WriteLine($"{code},{responseBody}");
                    }

                }

                return RedirectToPage("./Index", "Index");// RedirectToPage("./ShowExcel");

            }
            catch (Exception ex)
            {

                return RedirectToPage("./Error", "ShowError", new { message = ex.Message });

            }

        }

    }
}

GeoLocation/Pages/Downloads.cshtml
@page "{handler?}/{request?}"
@using GeoLocation.Models;

@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@model GeoLocation.Pages.DownloadsModel
@{
    ViewData["Title"] = "Home page";
}
<script type="text/javascript">
    function cbOnChanged(e) {
        if (e != undefined && e != null) {
            $('#btnDeleteFileForAll').attr('formaction', "DeleteFile/" + $(e).attr('asp-route-request'));
            $('#btnDownloadFile').attr('formaction', "DownloadFile/" + $(e).attr('asp-route-request'));

            $(':checkbox').each(function () {
                if (this.id != $(e)[0].id)
                this.checked = false;
            });

            //for (var chk in $('input:checkbox')) {
            //    if ($('input:checkbox')[chk].id != $(e)[0].id) {
            //        $('input:checkbox')[chk].checked = false;
            //    }
            //}
        }
    }
</script>
<style>
    .border333 {
        border-radius: 3px;
        background-color: #f44336;
        color: white;
    }

    .border3 {
        border-radius: 3px;
        background-color: white;
        color: black;
        border: 2px solid #f44336;
    }

    .btn {
        background-color: #4CAF50;
        border: none;
        color: #FFFFFF;
        padding: 10px 25px;
        text-align: center;
        -webkit-transition-duration: 0.4s;
        transition-duration: 0.4s;
        margin: 16px 0 !important;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
        border-radius:15px;
    }

    .btnDelete {
        background-color: #f44110;
        border: none;
        color: #FFFFFF;
        padding: 10px 25px;
        text-align: center;
        -webkit-transition-duration: 0.4s;
        transition-duration: 0.4s;
        margin: 16px 0 !important;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
        border-radius: 15px;
    }

    .btnChoose {
        background-color: khaki ;
        border: none;
        color: black;
        padding: 10px 25px;
        text-align: center;
        -webkit-transition-duration: 0.4s;
        transition-duration: 0.4s;
        margin: 16px 0 !important;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
        border-radius: 15px;
    }

    .Process .Delete {
        transition-duration: 0.4s;
    }

    .btn:hover {
        background-color: #4CAF10; /* Green */
        color: white;
    }

    .btnDelete:hover {
        background-color: #f44336; 
        color: white;
    }
</style>

<body>
    @{
        <table class="table table-hover" quick-grid>
            <thead>
                <form method="post">
                <tr>
                    <th class="col-lg-8" quick-sort="Actions">
                        <input type="submit" asp-route-request="" class="btn border3 border333" title="This Button Works For Excel Files" value="Show Excel" id="btnProcessForAll" />
                    </th>
                    <th class="col-lg-8" quick-sort="Actions">
                        <input type="submit" asp-route-request="" class="btnDelete border3 border333" value="Delete" id="btnDeleteFileForAll" />
                    </th>

                    <th class="col-lg-8" quick-sort="Actions">
                        <input type="submit" asp-route-request="" class="btn border3 border333" value="Download" id="btnDownloadFile" />
                    </th>
                </tr>
                </form>
                <tr>
                    <th class="col-sm-1" quick-sort="Select">Select</th>
                    <th class="col-lg-2" quick-sort="Id">Row</th>
                    <th class="col-lg-2" quick-sort="Name">Name</th>
                    <th class="col-lg-3" quick-sort="Description ">Description </th>
                    <th class="col-lg-5" quick-sort="Url">Path</th>
                    <th class="col-lg-2" quick-sort="Extension">Extension</th>
                    <th class="col-lg-2" quick-sort="Size">Size</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.ListOfFiles != null && Model.ListOfFiles.Count > 0)
                    @foreach (var item in Model.ListOfFiles)
                    {
                        <tr class="@(item.Id%2==0?"border-info":"border-end")">
                            <td class="col-sm-2"><input type="checkbox" onchange="cbOnChanged(this)"  asp-route-request="@item.Name" name="chk_@item.Id" id="chk_@item.Id" /></td>
                            <td class="">@item.Id</td>
                            <td>@item.Name</td>
                            <td>@item.Description</td>
                            <td>@item.Url</td>
                            <td>@item.Extension</td>
                            <td>@item.Size</td>
                        </tr>
                    }

            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6" class="text-center" quick-paging></td>
                </tr>
            </tfoot>
        </table>
    }

    <form method="post" enctype="multipart/form-data">

        <span>Select File:</span>

        <input type="file" class="btnChoose border3 border333 " name="postedFiles" multiple />

        <input type="submit" value="Upload" class="btn border3 border333" asp-page-handler="Upload" />

        <br />

        @* <span>@Html.Raw(Model.Message)</span>*@

    </form>

</body>

GeoLocation/Pages/ShowExcel.cshtml
@page
@model GeoLocation.Pages.ShowExcelModel


<style>
    .button {
        display: inline-block;
        border-radius: 4px;
        background-color: darkolivegreen;
        border: none;
        color: #FFFFFF;
        text-align: center;
        font-size: 10px;
        padding: 2px;
        width: 20px;
        transition: all 0.5s;
        cursor: pointer;
        margin: 5px;
    }

        .button span {
            cursor: pointer;
            display: inline-block;
            position: relative;
            transition: 0.5s;
        }

            .button span:after {
                content: '\00bb';
                position: absolute;
                opacity: 0;
                top: 0;
                right: -20px;
                transition: 0.5s;
            }

        .button:hover span {
            padding-right: 3px;
        }

            .button:hover span:after {
                opacity: 1;
                right: 0;
            }

    .border333 {
        border-radius: 3px;
        background-color: #f44336;
        color: white;
    }

    .border3 {
        border-radius: 3px;
        background-color: white;
        color: black;
        border: 2px solid #f44336;
    }

    .btnGeoLocation {
        background-color: #4CAF50;
        border: none;
        color: #FFFFFF;
        padding: 10px 25px;
        text-align: center;
        -webkit-transition-duration: 0.4s;
        transition-duration: 0.4s;
        margin: 16px 0 !important;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
        border-radius: 15px;
    }

    .btnCancelGeoLocation {
        background-color: navajowhite;
        border: none;
        color: #FFFFFF;
        padding: 10px 25px;
        text-align: center;
        -webkit-transition-duration: 0.4s;
        transition-duration: 0.4s;
        margin: 16px 0 !important;
        text-decoration: none;
        font-size: 16px;
        cursor: pointer;
        border-radius: 15px;
    }
</style>

@{
    <table class="table table-hover" quick-grid>
        <thead>
            <tr style="width:50px!important">
                <form method="post">
                <td>
                    <input type="submit" formmethod="post" asp-route-filename="@ViewData["Sended_File"]" asp-page-handler="GetLocations" id="btnGeoLocation" value="Get GeoLocation" class="btnGeoLocation border3 border333" />
                    <input type="submit" formmethod="post" asp-route-filename="@ViewData["Sended_File"]" asp-page-handler="CancelExcelFileProcessed" id="btnCancelRequestGeoLocation" value="Cancel GeoLocation Process" class="btnCancelGeoLocation border3 border333" />
                    <input type="hidden" id="fileForProcess" name="fileForProcess" asp-data-filename="@ViewData["Sended_File"]" />
                </td>
              </form>
              <form method="post">
                <td>
                    <div style="display:inline-flex">
                        <input type="submit" value="<<" class="button" title="First" formmethod="get" asp-page-handler="FirstData">

                        <input type="submit" value="<" class="button" title="Previous" asp-route-current="@Model.Current" asp-page-handler="PreviousData">

                        <span name="current" data-current="@Model.Current">@Model.Current</span>

                        <input type="submit" value=">" class="button" title="Next" asp-route-current="@Model.Current" asp-page-handler="NextData">

                        <input type="submit" value=">>" class="button" title="End" asp-route-current="@Model.Current" asp-page-handler="EndData">

                    </div>
                </td>
                </form>
            </tr>
            <tr>
                <th class="col-sm-1" quick-sort="State">         State      </th>
                <th class="col-lg-2" quick-sort="Area">          Area     </th>
                <th class="col-lg-2" quick-sort="SchoolName">    SchoolName     </th>
                <th class="col-lg-3" quick-sort="LevelStudy">    LevelStudy    </th>
                <th class="col-lg-5" quick-sort="Gender ">       Gender      </th>
                <th class="col-lg-2" quick-sort="SchoolType">    SchoolType     </th>
                <th class="col-lg-2" quick-sort="Type ">         Type      </th>
                <th class="col-lg-2" quick-sort="Character ">    Character      </th>
                <th class="col-lg-2" quick-sort="Phone ">        Phone      </th>
                <th class="col-lg-2" quick-sort="Postalcode">
                    <form method="post">
                        <div class="d-sm-inline-flex">

                            <button type="submit" class="btn" asp-route-Sort="asc" asp-route-data="@Model.Current" asp-page-handler="SortData">
                                <svg onclick="" src="/css/sort-down-alt.svg" width="16" height="16" fill="currentColor" class="bi bi-sort-down-alt" viewBox="0 0 16 16">
                                    <path d="M3.5 3.5a.5.5 0 0 0-1 0v8.793l-1.146-1.147a.5.5 0 0 0-.708.708l2 1.999.007.007a.497.497 0 0 0 .7-.006l2-2a.5.5 0 0 0-.707-.708L3.5 12.293V3.5zm4 .5a.5.5 0 0 1 0-1h1a.5.5 0 0 1 0 1h-1zm0 3a.5.5 0 0 1 0-1h3a.5.5 0 0 1 0 1h-3zm0 3a.5.5 0 0 1 0-1h5a.5.5 0 0 1 0 1h-5zM7 12.5a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 0-1h-7a.5.5 0 0 0-.5.5z" />
                                </svg>
                            </button>
                            <span style="vertical-align:middle;text-align:center;padding:.475rem .02rem"> Postalcode</span>
                            <button type="submit" class="btn" asp-route-Sort="desc" asp-route-data="@Model.Current" asp-page-handler="SortData">
                                <svg src="/css/sort-up.svg" width="16" height="16" fill="currentColor" class="bi bi-sort-up" viewBox="0 0 16 16">
                                    <path d="M3.5 12.5a.5.5 0 0 1-1 0V3.707L1.354 4.854a.5.5 0 1 1-.708-.708l2-1.999.007-.007a.498.498 0 0 1 .7.006l2 2a.5.5 0 1 1-.707.708L3.5 3.707V12.5zm3.5-9a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zM7.5 6a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zm0 3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1h-3zm0 3a.5.5 0 0 0 0 1h1a.5.5 0 0 0 0-1h-1z" />
                                </svg>
                            </button>

                        </div>
                    </form>
                </th>
                <th class="col-lg-2" quick-sort="Address ">      Address      </th>
            </tr>
        </thead>
        <tbody>
            @if (Model.GridData != null && Model.GridData.Count > 0)
                @foreach (var item in Model.GridData)
                {
                    <tr class="">
                        <td>@item.State 	   </td>
                        <td>@item.Area         </td>
                        <td>@item.SchoolName   </td>
                        <td>@item.LevelStudy   </td>
                        <td>@item.Gender       </td>
                        <td>@item.SchoolType   </td>
                        <td>@item.Type         </td>
                        <td>@item.Character    </td>
                        <td>@item.Phone        </td>
                        <td>@item.Postalcode   </td>
                        <td>@item.Address      </td>
                    </tr>
                }

        </tbody>
        <tfoot>
            <tr>
                <td colspan="6" class="text-center" quick-paging></td>
            </tr>
        </tfoot>
    </table>
}